### ISSUE TITLE
提几点想法

### ISSUE THREAD

**Issue by slove** [UISSH/backend#22]
1.多网站需求
2.网站主目录自定义
3.防火墙端口开放自定义
3.php版本自定义
4.网站自定义备份

**Comment by zmaplex** [comment]
1.多网站需求是什么意思呢？

2.网站主目录这个不会被设计成自定义的，只能由系统分配。这个是强制规范，为后续一键迁移考虑的。

3.目前没有集成防火墙规则，未来几个版本会有的。

4.php 指定版本，这个涉及到多版本共存，因为本项目的宗旨就是尽可能的遵循发行版走提供一个基础系统平台，客制化的多版本 php 可以交给第三方脚本负责，会考虑提供一个 api 来切换 php 版本。

5.网站自定义备份是下一个版本的计划

**Comment by slove** [comment]
多网站需求，就是在一个主机上建一个blog，论坛多个网站意思

**Comment by zmaplex** [comment]
> 多网站需求，就是在一个主机上建一个blog，论坛多个网站意思

这个本来就支持

**Comment by slove** [comment]
还想提个需求，就是网站支持自定义二级目录（因为部分程序需要指定二级目录作为运行目录，如ThinkPHP5，Laravel）

**Comment by zmaplex** [comment]
> 还想提个需求，就是网站支持自定义二级目录（因为部分程序需要指定二级目录作为运行目录，如ThinkPHP5，Laravel）

这个特定的网站程序可以由对应的插件来创建，二级目录也会被插件接管来管理。

**Comment by zmaplex** [comment]
> 还想提个需求，就是网站支持自定义二级目录（因为部分程序需要指定二级目录作为运行目录，如ThinkPHP5，Laravel）

还有一种情况就是站点用一个域名，不同子目录域名对应不同网站程序，这个未来需要考虑，谢谢建议

**Comment by slove** [comment]
还是非常感谢你做出这么好的程序，赞👍
